
### Check Username Availability
GET https://media2.edu.metropolia.fi/restaurant/api/v1/users/available/aleksi999
Content-Type: application/json

### Register a new user
POST https://media2.edu.metropolia.fi/restaurant/api/v1/users
Content-Type: application/json

{
    "username": "aleksi999",
    "password": "password123",
    "email": "23aleksi999@mail.com"
}

### login with username and password
POST https://media2.edu.metropolia.fi/restaurant/api/v1/auth/login
Content-Type: application/json

{
  "username": "aleksi99",
  "password": "password123"
}


### Update user information
PUT https://media2.edu.metropolia.fi/restaurant/api/v1/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFsZWtzaTk5OSIsImVtYWlsIjoiMjNhbGVrc2k5OTlAbWFpbC5jb20iLCJfaWQiOiI2N2YzZWRiZDcyNWRmZjM2MDk4NzkwMTUiLCJyb2xlIjoidXNlciIsImFjdGl2YXRlZCI6dHJ1ZSwiaWF0IjoxNzQ0MDQxNTUzfQ.9zyS8pm6Iot7a2g4qbnh833HH-EETCW9cgIDjSNLkQw

{
    "username": "aleksi99",
    "password": "password123"
}

### Delete user account
DELETE https://media2.edu.metropolia.fi/restaurant/api/v1/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFsZWtzaTk5OSIsImVtYWlsIjoiMjNhbGVrc2k5OTlAbWFpbC5jb20iLCJfaWQiOiI2N2YzZWRiZDcyNWRmZjM2MDk4NzkwMTUiLCJyb2xlIjoidXNlciIsImFjdGl2YXRlZCI6dHJ1ZSwiaWF0IjoxNzQ0MDQxNTUzfQ.9zyS8pm6Iot7a2g4qbnh833HH-EETCW9cgIDjSNLkQw



### get user account
GET https://media2.edu.metropolia.fi/restaurant/api/v1/users/token
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFsZWtzaTkiLCJlbWFpbCI6ImFsZWtzaTk5OTlAbWFsby5jb20iLCJfaWQiOiI2N2Y0ZGE5YTcyNWRmZjM2MDk4Nzk1NzYiLCJyb2xlIjoidXNlciIsImFjdGl2YXRlZCI6dHJ1ZSwiYXZhdGFyIjoiYTE1MDNiNmEyYjM4ZDExYTYzN2EwYWVkOTM0MDQ2NDkiLCJpYXQiOjE3NDQxMjg3MTd9.ZG9o5s6zPIJT-CkRLuUb19MAqypnSAc082uuiuAv2N0


### get user account
GET https://media2.edu.metropolia.fi/restaurant/api/v1/users/token/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFsZWtzaTkiLCJlbWFpbCI6ImFsZWtzaTk5OTlAbWFsby5jb20iLCJfaWQiOiI2N2Y0ZGE5YTcyNWRmZjM2MDk4Nzk1NzYiLCJyb2xlIjoidXNlciIsImFjdGl2YXRlZCI6dHJ1ZSwiYXZhdGFyIjoiYTE1MDNiNmEyYjM4ZDExYTYzN2EwYWVkOTM0MDQ2NDkiLCJpYXQiOjE3NDQxMjg3MTd9.ZG9o5s6zPIJT-CkRLuUb19MAqypnSAc082uuiuAv2N0


### Get restaurant list
GET https://media2.edu.metropolia.fi/restaurant/api/v1/restaurants

Content-Type: application/json


### Get Weekly Menu for a Restaurant
GET https://media2.edu.metropolia.fi/restaurant/api/v1/restaurants/weekly/{id}/{lang}
Content-Type: application/json

# Replace {id} with the actual restaurant ID and {lang} with the desired language ('en' or 'fi').
# Example:
# GET https://media2.edu.metropolia.fi/restaurant/api/v1/restaurants/weekly/12345/fi


### Get Weekly Menu for Restaurant ID 12345 in Finnish
GET https://media2.edu.metropolia.fi/restaurant/api/v1/restaurants/weekly/6470d38ecb12107db6fe24c2/fi
Content-Type: application/json



### Get Weekly Menu for Restaurant ID 12345 in Finnish
GET https://media2.edu.metropolia.fi/restaurant/api/v1/restaurants/weekly/6470d38ecb12107db6fe24c4/fi
Content-Type: application/json


